[build]
  base = "/"
  command = "pnpm build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "10.2.4"
  PNPM_VERSION = "8.12.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
    output_path = "reports/lighthouse.html"
    urls = [
      "/",
      "/posts/chart-types-bar",
      "/posts/chart-types-line",
      "/posts/chart-types-pie"
    ]
    [plugins.inputs.thresholds]
      performance = 0.8
      accessibility = 0.9
      best-practices = 0.9
      seo = 0.9
      pwa = 0.5

[[redirects]]
  from = "/*"
  to = "/"
  status = 200