[build]
  command = "pnpm build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

[[plugins]]
[plugins."@netlify/plugin-lighthouse"]
  audit_url = "/"

  [plugins."@netlify/plugin-lighthouse".thresholds]
    performance = 0.8
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9

[[redirects]]
  from = "/*"
  to = "/"
  status = 200