[build]
  command = "pnpm build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "10.2.4"
  PNPM_VERSION = "8.12.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
    output_path = "reports/lighthouse.html"
    urls = [
      "/"
    ]
    [plugins.inputs.thresholds]
      performance = 0.7
      accessibility = 0.8
      best-practices = 0.8
      seo = 0.8
      pwa = 0.0

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200