[build]
  command = "pnpm build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "10.2.4"  # Latest stable npm version
  PNPM_VERSION = "8.12.0" # Latest stable pnpm version

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
    output_path = "reports/lighthouse.html"
    # Audit only the deployed URL and important pages
    urls = [
      "/",
      "/posts/chart-types-bar",
      "/posts/chart-types-line",
      "/posts/chart-types-pie"
    ]
    # Fail build if performance score drops below these thresholds
    [plugins.inputs.thresholds]
      performance = 0.8
      accessibility = 0.9
      best-practices = 0.9
      seo = 0.9
      pwa = 0.5

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200