[build]
  command = "pnpm build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_FLAGS = "--version" # Prevent Netlify npm install

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 